### ISSUE TITLE
Form Validation could be added

### ISSUE THREAD

**Issue by SouradipAdhikari03** [RayaBasu01/neumorph_login#1]
This login page [https://rayabasu01.github.io/neumorph_login/#](url), the form is not validating data, form validation could be added

**Comment by ETdan** [comment]
hello there i can help you with the form validation so assign it to me

**Comment by RayaBasu01** [comment]
Sure @ETdan  All the best

**Comment by ETdan** [comment]
Thank you for the opportunity. Can you please tell me where in the form you want the error messages to aper, I don't want to ruin the style.
